name: Deploy LLA server to Heroku

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
          
      # - name: Login to Heroku
      #   uses: akhileshns/heroku-deploy@v3.12.14
      #   with: 
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: llapp
      #     heroku_email: nhinlechi@gmail.com

      # - name: Build and Deploy to Heroku
      #   run: |
      #     heroku container:login
      #     heroku container:push web -a llapp
      #     heroku container:release web -a llapp
